// client/src/components/EvalBar.tsx
import { Analysis } from "../types/Types";
import Centered from "./Centered";
import EvalBarSeg from "./EvalBarSeg";

function calculateXHeight(evaluation: string) {
    switch (evaluation) {
        case "XWins":
            return 24;
        case "OWins":
            return 0;
        case "Draw":
            return 12;
        default:
            return 0;
    }
}

function evalText(evaluation: string) {
    switch (evaluation) {
        case "XWins":
            return "X Win";
        case "OWins":
            return "O Win";
        case "Draw":
            return "0.0";
        default:
            return null;
    }
}

interface Props {
    analysis: Analysis | null;
}

function EvalBar({ analysis }: Props) {
    const evaluation = analysis?.eval ?? "Draw";
    const xEvalHeight = calculateXHeight(evaluation);

    return (
        <Centered className="w-8 h-96 border border-black mr-2">
            <EvalBarSeg
                className="bg-red-600"
                style={{
                    height: `${24 - xEvalHeight}rem`,
                    transform: `translateY(-${xEvalHeight / 2}rem)`,
                }}
            />
            <p className="text-white font-comic-sans z-10 text-xs text-center">
                {evalText(evaluation)}
            </p>
            <EvalBarSeg
                className="bg-blue-600"
                style={{
                    height: `${xEvalHeight}rem`,
                    transform: `translateY(${(24 - xEvalHeight) / 2}rem)`,
                }}
            />
        </Centered>
    );
}

export default EvalBar;

// client-svelte/src/components/EvalBar.svelte
<script>
    export let analysis;

    $: xEvalHeight = calculateXHeight(analysis.eval);
    $: evalText = getEvalText(analysis.eval);

    function getEvalText(evaluation) {
        switch (evaluation) {
            case "XWins":
                return "X Win";
            case "OWins":
                return "O Win";
            case "Draw":
                return "0.0";
            default:
                return null;
        }
    }

    function calculateXHeight(evaluation) {
        switch (evaluation) {
            case "XWins":
                return 300;
            case "OWins":
                return 0;
            default:
                return 150;
        }
    }
</script>

<div class="eval-bar">
    <div
        class="fill red"
        style:height={`${300 - xEvalHeight}px`}
        style:transform={`translateY(-${xEvalHeight / 2}px)`}
    />
    <p>{evalText || "?"}</p>
    <div
        class="fill blue"
        style:height={`${xEvalHeight}px`}
        style:transform={`translateY(${150 - xEvalHeight / 2}px)`}
    />
</div>

<style>
    .eval-bar {
        width: 20px;
        height: 300px;
        border: 1px solid black;
        margin: 0 20px;
        box-sizing: border-box;
        display: flex;
        align-items: center;
        justify-content: center;
    }

    p {
        z-index: 10;
        color: white;
        font-family: "Comic Sans MS", "Times New Roman";
        font-size: 9px;
        text-align: center;
    }

    .fill {
        width: 20px;
        height: 150px;
        position: absolute;
        transition: 1s;
    }

    .fill.red {
        background-color: red;
    }

    .fill.blue {
        background-color: blue;
    }
</style>
