// client-svelte/src/pages/MainPage.svelte
<script>
    import { PROXY } from "../main";
    import Board from "../components/Board.svelte";
    import EvalBar from "../components/EvalBar.svelte";
    import { Navigate } from "svelte-router-spa";

    let board = default_board();
    let turn = "X";
    let analysis = {};
    let winText = "";

    $: fetchAnalysis(board, turn).then(res => (analysis = res));
    $: gameEnded = !!analysis.moves && !analysis.moves.length;
    $: winText = getWinText(analysis.eval);

    async function fetchAnalysis(board, turn) {
        const res = await fetch(`${PROXY}/api/analysis`, {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({
                board,
                turn,
            }),
        });

        return await res.json();
    }

    function restart() {
        analysis = {};
        board = default_board();
        turn = "X";
    }

    function default_board() {
        return [
            [null, null, null],
            [null, null, null],
            [null, null, null],
        ];
    }

    function getWinText(evaluation) {
        switch (evaluation) {
            case "Draw":
                return "It's a draw!";
            case "XWins":
                return "The winner is X!";
            case "OWins":
                return "The winner is O!";
        }
    }
</script>

<div class="main-page">
    <Navigate to="board-editor"><button class="board-editor">Board Editor</button></Navigate>

    <div class="game">
        <EvalBar {analysis} />
        <Board bind:board bind:turn {gameEnded} />
    </div>

    <div class="info">
        {#if !gameEnded}
            <h3>{turn}'s turn</h3>
        {:else}
            <h2>{winText}</h2>
            <button on:click={restart}>Restart</button>
        {/if}
    </div>
</div>

<style>
    .main-page {
        display: flex;
        align-items: center;
        justify-content: center;
        width: 100vw;
        height: 100vh;
        flex-direction: column;
    }

    .game {
        display: flex;
    }

    h2,
    h3 {
        text-align: center;
    }

    button {
        margin: 0 auto;
        width: 100%;
        height: 30px;
    }

    button.board-editor {
        width: 300px;
        margin-bottom: 20px;
    }
</style>

// client/src/pages/MainPage.tsx
import React from "react";
import EvalBar from "../components/EvalBar";
import TicTacToe from "../components/TicTacToe";
import { Analysis, Board, Turn } from "../types/Types";

export const DEFAULT_BOARD: Board = [
    [null, null, null],
    [null, null, null],
    [null, null, null],
];

interface Props {}

interface State {
    turn: Turn;
    board: Board;
    analysis: Analysis | null;
}

class MainPage extends React.Component<Props, State> {
    constructor(props: Props) {
        super(props);

        this.state = {
            turn: "X",
            board: DEFAULT_BOARD,
            analysis: null,
        };
    }

    componentDidUpdate(prevProps: Props, prevState: State) {
        if (this.state.board !== prevState.board) {
            this.fetchAnalysis();
        }
    }

    async fetchAnalysis() {
        const analysis = await fetch("/api/analysis", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({
                board: this.state.board,
                turn: this.state.turn,
            }),
        });

        const json = await analysis.json();

        this.setState({ analysis: json });
    }

    componentDidMount() {
        this.fetchAnalysis();
    }

    render() {
        const { analysis, turn, board } = this.state;

        return (
            <div className="flex items-center justify-center flex-col w-screen h-screen">
                <button className="editor-button">Board Editor</button>
                <div className="flex">
                    <EvalBar analysis={analysis} />
                    <TicTacToe
                        analysis={analysis}
                        turn={turn}
                        board={board}
                        setBoard={board => this.setState({ board })}
                        setTurn={turn => this.setState({ turn })}
                        setAnalysis={analysis => this.setState({ analysis })}
                    />
                </div>
            </div>
        );
    }
}

export default MainPage;
